"""Add cv_id to Criteria model

Revision ID: 30c4cf5ac0a6
Revises: bbfb517a40f1
Create Date: 2025-01-25 19:24:29.307125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30c4cf5ac0a6'
down_revision = 'bbfb517a40f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'cv', ['cv_id'], ['id'])

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('cv_id')

    # ### end Alembic commands ###
